sudo: required
services:
  - docker

before_install:
  - docker build -t michaelapp2017/docker-workflow -f Dockerfile.dev .

script:
  - docker run michaelapp2017/docker-workflow npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-workflow"
  env: "DockerWorkflow-env"
  bucket_name: "elasticbeanstalk-us-east-1-952439452167"
  bucket_path: "docker-workflow"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
