sudo: required
services:
  - docker

before_install:
  - docker build -t michaelapp2017/docker-workflow -f Dockerfile.dev .

script:
  - docker run stephengrider/docker-react npm run test -- --coverage
